name: niobiumecom
hooks:
  preprovision:
    shell: pwsh
    run: ./infra/scripts/SetAppSettings.ps1
  postprovision:
    shell: pwsh
    run: ./infra/scripts/ClearAppSettings.ps1
services:
  host:
    project: ./src/Niobium.AI.Host
    language: csharp
    host: containerapp
    docker:
      context: ../..
      path: ./Dockerfile
      registry: docker.io
      image: niobiumnz/niobiumecom
      tag: ${VERSION_MAJOR:-1}.${VERSION_MINOR:-0}.${GITHUB_RUN_NUMBER:-0-prerelease}
infra:
  provider: bicep
  layers:
    - name: niobiumecom-host
      path: ./infra