<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Executors\ProductVisual\ProductVisualBuilder.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Executors\CompetitorAnalysis\CompetitionScout.md" />
    <EmbeddedResource Include="Executors\MarketResearch\KeywordsExpander.md" />
    <EmbeddedResource Include="Executors\ProductDiscovery\ProductClusterer.md" />
    <EmbeddedResource Include="Executors\ProductNormalization\ProductNormalizer.md" />
    <EmbeddedResource Include="Executors\ProductProfile\ProductProfiler.md" />
    <EmbeddedResource Include="Executors\ProductVisual\ProductVisualBuilder.md" />
    <EmbeddedResource Include="Tools\dog-hair-removal.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Niobium.AI\Niobium.AI.csproj" />
  </ItemGroup>

</Project>
