name: Publish to Prod

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Run publish composite
        uses: ./.github/actions/container-app
        with:
          env_name: ${{ github.environment }}
          version_major: 1
          version_minor: 0
